config/routes.rb
Project::Application.routes.draw do
  resources :items

  resources :stores

  resources :wishlists

  resources :courses

  resources :users

  root "wishlists#index"
  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", :as => "logout"
  get "browse" => "wishlists#browse", :as => "browse"

end

app/models/store.rb
class Store
  include Mongoid::Document

  has_many :items, as: :container

  field :name, type: String
  field :url, type: String
  field :shipping_min, type: Float

  validates :url, :presence => true
  validates :name, :presence => true
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_filter :admin_only, :only => [:index, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to new_wishlist_path, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    while Wishlist.find_by(store_id: @store.id) != nil do
      w = Wishlist.find_by(store_id: @store.id)
      w.destroy
    end
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :url, :shipping_min)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :shipping_min %><br>
    <%= f.text_field :shipping_min %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<div class="page-header">
  <h1>All stores</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Store</th>
      <th>Url</th>
      <th>Shipping min</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.url %></td>
        <td><%= store.shipping_min %></td>
        <td><%= link_to 'View/Edit', edit_store_path(store), :class => 'btn btn-mini' %></td>
        <td><%= link_to 'Delete', store, method: :delete, data: { confirm: 'Are you sure? All associated wishlists will also be deleted.' }, :class => 'btn btn-mini' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path, :class => 'btn btn-primary' %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back to Wishlists', root_url %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @store.url %>
</p>

<p>
  <strong>Shipping min:</strong>
  <%= @store.shipping_min %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>