config/routes.rb
Project::Application.routes.draw do
  resources :items

  resources :stores

  resources :wishlists

  resources :courses

  resources :users

  root "wishlists#index"
  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", :as => "logout"
  get "browse" => "wishlists#browse", :as => "browse"

end

app/models/item.rb
class Item
  include Mongoid::Document

  belongs_to :container, polymorphic: true

  field :name, type: String
  field :url, type: String
  field :price, type: Float

  validates :url, :presence => true
  validates :container, :presence => true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @wishlist = Wishlist.find(session[:wishlist_id])
    params[:item].delete :container
    item = Item.find_by(url: params[:item][:url])
    if !item
      item = Item.new(item_params)
      item.container_type = 'Store'
      item.container_id = @wishlist.store.id
    end
    @item = item

    item2 = Item.new(item_params)
    item2.container_type = 'Wishlist'
    item2.container_id = @wishlist.id
    @item2 = item2

    respond_to do |format|
      if @item.save && @item2.save
        @wishlist.items << @item2
        @wishlist.save
        format.html { redirect_to edit_wishlist_url(@wishlist), notice: 'Item was successfully added to wishlist.' }
        #format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    if @item.container_type == 'Wishlist'
      @wishlist = Wishlist.find(@item.container_id)
      @wishlist.items.delete_if{|o| o.id == @item.id}
      @wishlist.save
    elsif @item.container_type == 'Store'
      @store = Store.find(@item.container_id)
      @store.items.delete_if{|o| o.id == @item.id}
      @store.save
    end

    @item.destroy
    respond_to do |format|
      @wishlist = Wishlist.find(session[:wishlist_id])
      format.html { redirect_to edit_wishlist_url(@wishlist) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :url, :price, :container)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="page-header">
  <h1>All items</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Item</th>
      <th>Url</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.url %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'View/Edit', edit_item_path(item), :class => 'btn btn-mini' %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path, :class => 'btn btn-primary' %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', wishlists_url %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @item.url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>