config/routes.rb
Project::Application.routes.draw do
  resources :items

  resources :stores

  resources :wishlists

  resources :courses

  resources :users

  root "wishlists#index"
  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", :as => "logout"
  get "browse" => "wishlists#browse", :as => "browse"

end

app/models/wishlist.rb
class Wishlist
  include Mongoid::Document
  before_save :calculate_total

  belongs_to :user
  belongs_to :store
  has_many :items, as: :container

  field :want_by, type: Date
  field :total_cost, type: Float, default: 0

  validates :user, :presence => true
  validates :store, :presence => true
  validates_associated :user
  validates_associated :store
  #validates :items, :length => { :minimum => 1 }

  def calculate_total
    x = 0
    self.items.each do |item|
      x = x + item.price
    end
    self.total_cost = x;
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]

  # GET /wishlists
  # GET /wishlists.json
  def index
    @wishlists = Wishlist.all
  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
  end

  # GET /wishlists/new
  def new
    @wishlist = Wishlist.new
  end

  # GET /wishlists/1/edit
  def edit
  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    d = Date.civil(params[:wishlist]['want_by(1i)'].to_i, params[:wishlist]['want_by(2i)'].to_i, params[:wishlist]['want_by(3i)'].to_i)
    params[:wishlist].delete 'want_by(1i)'
    params[:wishlist].delete 'want_by(2i)'
    params[:wishlist].delete 'want_by(3i)'
    wishlist = Wishlist.new
    wishlist.want_by = d
    wishlist.total_cost = 0
    wishlist.store_id = params[:wishlist][:store]

    @current_user = User.find(session[:user_id])
    wishlist.user_id = @current_user.id

    @wishlist = wishlist

    respond_to do |format|
      if @wishlist.save
        format.html { redirect_to wishlists_url, notice: 'Wishlist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wishlist }
      else
        format.html { render action: 'new' }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlists/1
  # PATCH/PUT /wishlists/1.json
  def update
    respond_to do |format|
      if @wishlist.update(wishlist_params)
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  def browse
    @wishlists = Wishlist.all
  end

  # DELETE /wishlists/1
  # DELETE /wishlists/1.json
  def destroy
    @wishlist.destroy
    respond_to do |format|
      format.html { redirect_to wishlists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist
      @wishlist = Wishlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wishlist_params
      params.require(:wishlist).permit(:want_by, :total_cost, :store)
    end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_browse.html.erb
<div class="page-header">
<h1>All wishlists</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Store</th>
      <th>Order By</th>
      <th>Total Price</th>
      <th>Order To</th>
      <th>User</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlists.each do |wishlist| %>
      
        <tr>
          <td><%= link_to wishlist.store.name, wishlist.store.url %></td>
          <td><%= wishlist.want_by %></td>
          <td><%= wishlist.total_cost %></td>
          <% if false %><td><%= '%.2f' % (wishlist.store.shipping_min - wishlist.total_cost) %></td><%end%>
          <% if wishlist.user.building != nil %>
          <td><%= wishlist.user.building %></td>
          <% else %>
          <td>--</td>
          <% end %>
          <td><%= link_to wishlist.user.first_name, wishlist.user %></td>
          <td><a class="btn btn-mini" href="mailto:<%= wishlist.user.email%>?Subject=Let's%20share%20an%20order!">Email <%= wishlist.user.first_name %></a>
          </td>

          <td><%= link_to 'View', wishlist, :class => 'btn btn-mini' %></td>
        </tr>
      
    <% end %>
  </tbody>
</table>

<br>

app/views/wishlists/_form.html.erb
<%= form_for(@wishlist) do |f| %>
  <% if @wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
      <% @wishlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= f.label :want_by %><br>
    <%= f.date_select :want_by %>
  </div>
  <% if action_name == 'new' %>
    <div class="field">
    <%= f.label :store %><br>
    <%= f.collection_select :store, Store.all, :id, :name %>
    <td><%= link_to 'Add a new store', new_store_path, :class => 'btn btn-mini' %></td>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishlists/browse.html.erb
<h1>All wishlists</h1>

<table>
  <thead>
    <tr>
      <th>Store name</th>
      <th>Want by</th>
      <th>Total cost</th>
      <th>Amount short</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlists.each do |wishlist| %>
      
        <tr>
          <td><%= wishlist.store.name %></td>
          <td><%= wishlist.want_by %></td>
          <td><%= wishlist.total_cost %></td>
          <td><%= '%.2f' % (wishlist.store.shipping_min - wishlist.total_cost) %></td>
          <td>Email <a href="mailto:<%= wishlist.user.email%>?Subject=Let's%20share%20an%20order!"><%= wishlist.user.first_name %></a>!</td>
          <td><%= link_to 'Show', wishlist %></td>
        </tr>
      
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wishlist', new_wishlist_path %>

app/views/wishlists/edit.html.erb
<div class="page-header">
  <h1><%= @wishlist.store.name %> wishlist</h1>
</div>


<% if false %>
<%= render 'form' %>
<% end %>

<div>
<p>
  <strong>Want by:</strong>
  <%= @wishlist.want_by %>
</p>

<p>
  <strong>Total cost:</strong>
  <%= @wishlist.total_cost %>
</p>
</div>


<% session[:wishlist_id] = @wishlist.id %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Item</th>
      <th>Price</th>
      <th></th>
    </tr>
  </thead>

  <tbody>

  	<% @wishlist.items.each do |item| %>
		<tr>
	      <td><a href="<%= item.url %>"><%= item.name %></a></td>
	      <td><%= item.price %></td>
	      <td><%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini' %></td>
	    </tr>
	<% end %>  

	<tr>
		<td>Total Price</td>
		<td><%= @wishlist.total_cost %></td>
	</tr>
  </tbody>
</table>

<br><%= link_to 'Add an item', new_item_path, :class => 'btn btn-primary' %><br><br>

<%= link_to 'Back', wishlists_path %>

app/views/wishlists/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tbody>
    <tr>
      <td>

<div class="page-header">
  <h1><%= @current_user.first_name %>'s wishlists</h1>
</div>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Store</th>
      <th>Order By</th>
      <th>Total Price</th>
      <th>Amount Required</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlists.each do |wishlist| %>
      <% if @current_user.email == wishlist.user.email %>
        <tr>
          <td><%= wishlist.store.name %></td>
          <td><%= wishlist.want_by %></td>
          <td><%= wishlist.total_cost %></td>
          <td><%= '%.2f' % (wishlist.store.shipping_min - wishlist.total_cost) %></td>
          
          <td><%= link_to 'View/Edit', edit_wishlist_path(wishlist), :class => 'btn btn-mini' %></td>
          <td><%= link_to 'Delete', wishlist, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini'%></td>
          <% if false %>
            <% wishlist.items.each do |item| %>
              <td><%= item.name %></td>
            <% end %>  
          <% end %>
        </tr>
      <% end %>  
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wishlist', new_wishlist_path, :class => 'btn btn-primary' %>



      </td>
      <td><%= render 'wishlists/browse' %></td>
    </tr>
  </tbody>
</table>

app/views/wishlists/new.html.erb
<h1>New wishlist</h1>

<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Back', wishlists_path %>

app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Want by:</strong>
  <%= @wishlist.want_by %>
</p>

<p>
  <strong>Total cost:</strong>
  <%= @wishlist.total_cost %>
</p>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Price</th>
      <th></th>
    </tr>
  </thead>

  <tbody>

  	<% @wishlist.items.each do |item| %>
		<tr>
	      <td><a href="<%= item.url %>"><%= item.name %></a></td>
	      <td><%= item.price %></td>
	    </tr>
	<% end %>  

	<tr>
		<td>Total Price</td>
		<td><%= @wishlist.total_cost %></td>
	</tr>
  </tbody>
</table>

<%= link_to 'Back', wishlists_path %>