config/routes.rb
Project::Application.routes.draw do
  resources :items

  resources :stores

  resources :wishlists

  resources :courses

  resources :users

  root "wishlists#index"
  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", :as => "logout"
  get "browse" => "wishlists#browse", :as => "browse"

end

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom">
  <div class="navbar-inner">
    <div class="container">
      <p class="text-muted"><br>Lucy He, Rails Spring 2014</p>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    <a class="brand"><%= link_to 'shopstop', root_url, :class => 'brand' %></a>  
	
      
      <div class="nav-collapse">
        <ul class="nav">
			<% if session[:user_id] == nil %>
				<% if  !(controller_name == 'sessions' && action_name == 'new') %>
					<li><%= link_to 'Login', login_path %></li>
				<% end %>
				<li><%= link_to 'Sign up now!', signup_path %></li>
			<% else %>
				<% @current_user = User.find_by(id: session[:user_id]) %>
				<li><%= link_to @current_user.first_name, edit_user_url(@current_user) %></li>
				<li><%= link_to 'Logout', logout_path %></li>
			<% end %>
        </ul>
      </div>
      
      <% if session[:user_id] != nil %>
        <% @current_user = User.find_by(id: session[:user_id]) %>
        <% if @current_user.role == 'admin' %>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Manage Users", users_url %></li>
            <li><%= link_to "Manage Stores", stores_url %></li>
          </ul>
        </div>
        <% end %>
      <% end %>   
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<div class="container">
<body>

<%= render 'layouts/navbar' %>
<%= yield %>
<%= render 'layouts/footer' %>

</body>
</div>
</html>